# Generated by Django 5.2.8 on 2025-11-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
