# Generated by Django 5.2.10 on 2026-04-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='completed',
        ),
        migrations.AddField(
            model_name='topic',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
